-- 그룹 함수2
-- SUM, AVG, MAX, MIN, COUNT

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY POSITION;

-- 학년(GRADE)별 평균 몸무게
SELECT GRADE, AVG(WEIGHT) -- 학년별 몸무게 평균
FROM STU
GROUP BY GRADE; 

SELECT GRADE, MAX(WEIGHT) -- 학년별 몸무게가 가장 높은 수치
FROM STU
GROUP BY GRADE; 

SELECT COUNT(*) -- 전체 레코드의 개수
FROM STUDENT;

SELECT COUNT(BONUS) --BONUS가 NULL이 아닌 레코드의 수
FROM PROFESSOR;

-- STUDENT테이블에서 각 학과의 학생수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
HAVING COUNT(*) >=4; -- GROUP함수의 조건을 주기위한 함수(WHERE랑 같지만 GROUP에서만 사용가능하다)

-- STEP 1. 각 학과에서 남자가 2명이상인 학과명, 학생수 출력
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT
HAVING COUNT(*) >= 2;
